version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    networks:
      - proxy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - homepage_config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: docker_default

volumes:
  homepage_config:
